version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/client
    ports:
      - 3000:3000
    image: app:rangeuserclient
    container_name: rangeuserclient_container
    command: npm start